
%
%  update_power_spectal_density_alt.m  ver 1.1  by Tom Irvine
%

function[cell_array]=update_power_spectral_density_alt()

            vars = evalin('base', 'whos');
            cell_array = cell(size(vars));
            for i=1:length(vars)
                cell_array{i} ='999';
                if(contains(vars(i).name,'myHandle') || ...
                   contains(vars(i).name,'vname_list') || ...
                   contains(vars(i).name,'Dirlik_N') || ...
                   strcmp(vars(i).name,'mode_1') || ...
                   strcmp(vars(i).name,'mode_2') || ...
                   strcmp(vars(i).name,'mode_3') || ...              
                   strcmp(vars(i).name,'mode_4') || ...
                   strcmp(vars(i).name,'mode_5') || ... 
                   strcmp(vars(i).name,'mode_6') || ...           
                   strcmp(vars(i).name,'two_dof_ModeShapes') || ...
                   strcmp(vars(i).name,'stress_th') || ...
                   strcmp(vars(i).name,'ans') || ...
                   contains(vars(i).name,'amp_cycles') || ...
                   contains(vars(i).name,'range_cycles') || ...
                   contains(vars(i).name,'amp_mean_cycles') || ...
                   contains(vars(i).name,'range_cycles_max_min')|| ...
                   strcmp(vars(i).name,'two_dof_mass') ||...
                   strcmp(vars(i).name,'point_mass_matrix') ||...
                   strcmp(vars(i).name,'dB_difference') ||...
                   contains(vars(i).name,'Hanning') ||...
                   contains(vars(i).name,'crash') ||...
                   contains(vars(i).name,'_trans_') ||...
                   contains(vars(i).name,'mspan_') ||...
                   contains(vars(i).name,'_trans') ||...
                   strcmp(vars(i).name,'sz'))          

                   cell_array{i} ='999';
                else    
                    ggg=evalin('base',vars(i).name);
                    sz=size(ggg);

                    try
                        mint2=min(ggg(:,2));
                        maxt2=max(ggg(:,2));

                        % fprintf(' %s  %8.4g  %8.4g  %d  \n',vars(i).name,mint2,maxt2,sz(2))
    
                        if(sz(2)==2 && mint2>=0 && maxt2<=1e+06)
                            cell_array{i} = vars(i).name;
                        else
                            cell_array{i} ='999';
                        end
                    catch
                        cell_array{i} ='999';
                    end    
                end    
            end
            for i=length(vars):-1:1
                if(contains(cell_array{i},'999'))
                    cell_array(i,:)=[];
                end
            end         